import { ContentType, PageType } from "./@types";

// https://kupu.maori.nz/set/Christmas

const Acknowledgement = ({
  dalle,
  reomaori,
  minidevs,
  kupu,
}: {
  dalle?: boolean;
  reomaori?: boolean;
  minidevs?: boolean;
  kupu?: boolean;
}) => {
  return (
    <>
      {dalle && (
        <div>
          Whakaahua na{" "}
          <a href="https://openai.com/dall-e-2/" target="_blank">
            DALL·E
          </a>{" "}
          - Image generated by{" "}
          <a href="https://openai.com/dall-e-2/" target="_blank">
            DALL·E
          </a>
        </div>
      )}
      {reomaori && (
        <div>
          <a href="https://www.reomaori.co.nz/te_ra_kirihimete" target="_blank">
            {" "}
            Te Rā Kirihimete - Christmas Day
          </a>
        </div>
      )}
      {minidevs && (
        <div>
          <a href="https://www.theminidevs.com" target="_blank">
            {" "}
            MiniDevs
          </a>
        </div>
      )}
      {kupu && (
        <div>
          <a href="https://kupu.maori.nz/set/Christmas" target="_blank">
            {" "}
            https://kupu.maori.nz/set/Christmas
          </a>
        </div>
      )}
    </>
  );
};

const pages: PageType[] = [
  {
    day: 1,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2009.23.27%20-%20waking%20up%20on%20Christmas%20morning%20in%20New%20Zealand.png",
    english: "Wake up!",
    maori: "E oho!",
    content: <div>Some extra content ...</div>,
    footer: <Acknowledgement dalle reomaori />,
    color: "#03a9f4",
  },
  {
    day: 2,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2009.26.18%20-%20waiting%20to%20open%20presents%20on%20Christmas%20day.png",
    english: "Hurry up please",
    maori: "Kia tere mai",
    footer: <Acknowledgement dalle reomaori />,
    color: "#4caf50",
  },
  {
    day: 3,
    author: "Annabelle",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/Te%20Reo%20Maori%20Christmas.jpg",
    english: "Let’s unwrap the presents",
    maori: "Kia hura tātou i ngā taonga",
    footer: <Acknowledgement reomaori minidevs />,
    color: "#ff9c07",
  },
  {
    day: 4,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2009.32.05%20-%20Weirdly%20shaped%20Christmas%20present%20that%20needs%20unwrapping%20carefully.png",
    english: "Open it carefully",
    maori: "Āta huraina",
    footer: <Acknowledgement dalle reomaori />,
    color: "#F44336",
  },
  {
    day: 5,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2009.48.51%20-%20Aren%27t%20you%20lucky%2C%20great%20Christmas%20present.png",
    english: "Aren’t you lucky!",
    maori: "Tō waimarie hoki!",
    footer: <Acknowledgement dalle reomaori />,
    color: "#673AB7",
  },
  {
    day: 6,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2011.45.23%20-%20New%20Zealand%20Christmas%20Lights%20city%20scape%20sky%20tower.png",
    english: "mārama Kirihimete",
    maori: "Christmas lights",
    footer: <Acknowledgement dalle kupu />,
    color: "#3F51B5",
  },
  {
    day: 7,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2011.48.33%20-%20Christmas%20carl%20singers%20on%20a%20new%20zealand%20beach.png",
    english: "Christmas carol",
    maori: "hīmene Kirihimete",
    footer: <Acknowledgement dalle reomaori />,
    color: "#03a9f4",
  },
  {
    day: 8,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2011.57.20%20-%20thank%20you%20for%20this%20present.png",
    english: "Thank you for this present",
    maori: "Tēnā koe i tēnei taonga",
    footer: <Acknowledgement dalle reomaori />,
    color: "#4caf50",
  },
  {
    day: 9,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.03.25%20-%20family%20happy%20christmas%20new%20zealand%20celebrate%20cartoon.png",
    english: "Merry Christmas to you and your whānau",
    maori: "Meri Kirihimete ki a koutou ko te whānau",
    footer: <Acknowledgement dalle reomaori />,
    color: "#ff9c07",
  },
  {
    day: 10,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.06.29%20-%20Christmas%20love%20heart%20chocolate%2C%20soft%20focus%2C%20romantic.png",
    english: "All I want for Christmas is you",
    maori: "Ko koe tāku e pīrangi nei mō te Kirihimete",
    footer: <Acknowledgement dalle reomaori />,
    color: "#F44336",
  },
  {
    day: 11,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.08.57%20-%20christmas%20table%20with%20christmas%20crackers%20laid%20out.png",
    english: "Should we open a Christmas cracker?",
    maori: "Me pakō i a tāua tētahi tiripapā Kirihimete?",
    footer: <Acknowledgement dalle reomaori />,
    color: "#673AB7",
  },
  {
    day: 12,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.11.54%20-%20reindeer%20eating%20carrots%20at%20christmas.png",
    english: "Did the reindeer eat the carrots?",
    maori: "I pau ngā kāroti i ngā tia a Hana Koko?",
    footer: <Acknowledgement dalle reomaori />,
    color: "#3F51B5",
  },
  {
    day: 13,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.13.15%20-%20plate%20of%20cookies%20%2C%20one%20with%20a%20bite%20taken%20out%20of%20it.png",
    english: "Did Santa eat his cookies?",
    maori: "I pau i a Hana Koko ana pihikete?",
    footer: <Acknowledgement dalle reomaori />,
    color: "#03a9f4",
  },
  {
    day: 14,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.16.29%20-%20a%20christmas%20feast%2C%20watching%20a%20clock%20on%20the%20wall.png",
    english: "When are we eating?",
    maori: "Āhea tātou kai ai?",
    footer: <Acknowledgement dalle reomaori />,
    color: "#4caf50",
  },
  {
    day: 15,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.18.01%20-%20a%20family%20at%20the%20beach%20in%20new%20zealand%20with%20crhistmas%20hats%20on.png",
    english: "What should we do today?",
    maori: "Me aha tātou i tēnei rā?",
    footer: <Acknowledgement dalle reomaori />,
    color: "#ff9c07",
  },
  {
    day: 16,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.19.51%20-%20A%20christmas%20card.png",
    english: "Christmas card",
    maori: "kāri Kirihimete",
    footer: <Acknowledgement dalle kupu />,
    color: "#F44336",
  },
  {
    day: 17,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.22.42%20-%20A%20traditional%20maori%20hangi.png",
    english: "Christmas feast",
    maori: "hākari Kirihimete",
    footer: <Acknowledgement dalle kupu />,
    color: "#673AB7",
  },
  {
    day: 18,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.23.45%20-%20Wrapping%20paper.png",
    english: "Wrapping paper",
    maori: "pepa ruruku",
    footer: <Acknowledgement dalle kupu />,
    color: "#3F51B5",
  },
  {
    day: 19,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.24.57%20-%20Pohutkawa%20tree%2C%20new%20zealand.png",
    english: "Christmas tree",
    maori: "rākau Kirihimete",
    footer: <Acknowledgement dalle kupu />,
    color: "#03a9f4",
  },
  {
    day: 20,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.26.46%20-%20new%20zealand%2C%20christmas%20decorations%20in%20a%20bach.png",
    english: "Decorations",
    maori: "whakapaipaitanga",
    footer: <Acknowledgement dalle kupu />,
    color: "#4caf50",
  },
  {
    day: 21,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.27.54%20-%20An%20angel%20on%20top%20of%20a%20christmas%20tree.png",
    english: "Angel",
    maori: "Anahera",
    footer: <Acknowledgement dalle kupu />,
    color: "#ff9c07",
  },
  {
    day: 22,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2012.30.01%20-%20Gift%2C%20in%20a%20new%20zealand%20fern%20forest.png",
    english: "Gift, present",
    maori: "Koha",
    footer: <Acknowledgement dalle kupu />,
    color: "#F44336",
  },
  {
    day: 23,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2011.41.18%20-%20A%20christmas%20stocking.png",
    english: "Christmas stocking",
    maori: "tōkena Kirihimete",
    footer: <Acknowledgement dalle kupu />,
    color: "#673AB7",
  },
  {
    day: 24,
    author: "DALL·E",
    contentType: ContentType.Image,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/Kirihimete/DALL%C2%B7E%202022-11-13%2011.37.00%20-%20Santa%20Claus%20surfing%20on%20a%20new%20Zealand%20beach.png",
    english: "Santa Claus",
    maori: "Hana Kōkō",
    footer: <Acknowledgement dalle kupu />,
    color: "#3F51B5",
  },
  {
    day: 25,
    author: "DALL·E",
    contentType: ContentType.Model,
    src: "https://mixiplycontent.blob.core.windows.net/jimbo0underscore0o365/scene.gltf",
    english: "Meri Kirihimete me te Hape Nū Ia!",
    maori: "Merry Christmas and a Happy New Year!",
    footer: <Acknowledgement dalle kupu />,
    color: "#03a9f4",
  },
];

export { pages };
